# This case study consists of 1000 marks and the solution file is expected to be submitted in the upcoming session for evaluation.

In [1]:
import numpy as np

### 1.Create two matrices of 3*3 and perform the arithmatic operations metioned in below "print" statements

In [24]:
mat1 = np.asmatrix(np.random.randint(1,9,(3,3)))
mat2 = np.asmatrix(np.random.randint(1,9,(3,3)))
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)


print("\nAddition\n------------------\n", mat1 +mat2)
print("\nMultiplication\n------------------\n", mat1 *mat2)


print("\nDivision\n------------------\n", mat1/mat2)
print("\nLinear combination: 3*A - 2*B\n-----------------------------\n", 3*mat1 -2*mat2)


print("\nAddition of a scalar (100)\n-------------------------\n", mat1+100)


print("\nExponentiation, matrix cubed here\n----------------------------------------\n", mat1**3)
print("\nExponentiation, mat1 sq-root using pow function\n-------------------------------------------\n",np.power(mat1,2))



1st Matrix of random single-digit numbers
----------------------------------------
 [[7 3 1]
 [6 6 5]
 [7 6 7]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[8 8 3]
 [4 2 8]
 [5 4 8]]

Addition
------------------
 [[15 11  4]
 [10  8 13]
 [12 10 15]]

Multiplication
------------------
 [[ 73  66  53]
 [ 97  80 106]
 [115  96 125]]

Division
------------------
 [[0.875      0.375      0.33333333]
 [1.5        3.         0.625     ]
 [1.4        1.5        0.875     ]]

Linear combination: 3*A - 2*B
-----------------------------
 [[ 5 -7 -3]
 [10 14 -1]
 [11 10  5]]

Addition of a scalar (100)
-------------------------
 [[107 103 101]
 [106 106 105]
 [107 106 107]]

Exponentiation, matrix cubed here
----------------------------------------
 [[ 991  666  502]
 [1792 1269 1030]
 [2134 1512 1231]]

Exponentiation, mat1 sq-root using pow function
-------------------------------------------
 [[49  9  1]
 [36 36 25]
 [49 36 49]]


Some operations, such as += and *=, act in place to modify an existing array rather than create a new one.

NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called “universal functions”(ufunc). Within NumPy, these functions operate elementwise on an array, producing an array as output.

### 2.Create two 3 * 3 matrices and perform the following operations as describe in print statement.

In [28]:
from numpy.random import randint as ri
mat1 = np.asmatrix(ri(1,9,(3,3)))
mat2 = np.asmatrix(ri(1,9,(3,3)))
print("\n1st Matrix of random single-digit numbers\n","-"*50,"\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n","-"*50,"\n",mat2)


print("\nSum of all numbers in 1st matrix\n","-"*50,"\n",np.sum(mat1))
print("\nSum of all numbers in columns of 1st matrix\n","-"*50,"\n",mat1[0][0].sum() + mat1[1].sum() +mat1[2].sum())


print("\nSum of all numbers in rows of 1st matrix\n","-"*50,"\n",mat1[0].sum() + mat1[1].sum() + mat1[2].sum())
print("\nProduct of all numbers in rows of 1st matrix\n","-"*50,"\n",mat1[0].prod() * mat1[1].prod() * mat1[2].prod())


print("\nProduct of all numbers in columns of 2nd matrix\n","-"*50,"\n",mat1[0][0].prod() * mat1[1].prod() * mat1[2].prod())
print("\nMean of all numbers in 1st matrix\n","-"*50,"\n",mat1.mean())


print("\nStandard deviation of all numbers in 1st matrix\n","-"*50,"\n",mat1.std())


mat1 = np.asmatrix(ri(1,99,(3,3)))
print("\nModified matrix of random numbers from 1 to 99\n","-"*50,"\n",mat1)


print("\nStandard deviation of all numbers in the modified matrix, a larger number\n","-"*80,"\n",mat1.std(),",", mat1.max())


print("\nVariance of all numbers in the modified matrix, a larger number\n","-"*80,"\n",mat1.var(),",",mat1.max())


print("\nMedian of all numbers in the modified matrix\n","-"*60,"\n",np.median(mat1.reshape(1,9)))



1st Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[7 1 8]
 [2 8 6]
 [2 2 6]]

2nd Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[8 2 3]
 [6 8 1]
 [6 1 5]]

Sum of all numbers in 1st matrix
 -------------------------------------------------- 
 42

Sum of all numbers in columns of 1st matrix
 -------------------------------------------------- 
 42

Sum of all numbers in rows of 1st matrix
 -------------------------------------------------- 
 42

Product of all numbers in rows of 1st matrix
 -------------------------------------------------- 
 129024

Product of all numbers in columns of 2nd matrix
 -------------------------------------------------- 
 129024

Mean of all numbers in 1st matrix
 -------------------------------------------------- 
 4.666666666666667

Standard deviation of all numbers in 1st matrix
 -------------------------------------------------- 
 2.70801280154532

Modified matr

###  3.Create a 3 \* 3 Matrix and Modify its shape to 9\*1 matrix.

In [40]:
##Solution
mat1 = np.asmatrix(ri(1,100,(3,3)))
print(mat1)
mat1.reshape(9,1)

[[44 25 55]
 [ 3 67  3]
 [60 73 52]]


matrix([[44],
        [25],
        [55],
        [ 3],
        [67],
        [ 3],
        [60],
        [73],
        [52]])

### 4.Sort

In [55]:
A = ri(1,100,10) # Vector of random interegrs
print("\nVector of 10 random integers from 1 to 100\n",'-'*50,"\n",A)
print("\nHere is the sorted vector\n",'-'*50,"\n",np.sort(A))



Vector of 10 random integers from 1 to 100
 -------------------------------------------------- 
 [66 12  7 46 31  5 76 47 22 64]

Here is the sorted vector
 -------------------------------------------------- 
 [ 5  7 12 22 31 46 47 64 66 76]


In [62]:
M = np.asmatrix(ri(1,100,(5,5))) #  5*5 Matrix of random interegrs
print("\n5x5 Matrix of random integers\n",'-'*50,"\n",M)
print("\nHere is the sorted matrix along each row\n",'-'*50,"\n",np.sort(M)) # Default axis =1
print("\nHere is the sorted matrix along each column\n",'-'*50,"\n",np.sort(M,axis=0))


5x5 Matrix of random integers
 -------------------------------------------------- 
 [[14 10 63 44 59]
 [60 11 37 38 61]
 [26 56 94 75  8]
 [39 40 35 12 45]
 [44 69 27  8 55]]

Here is the sorted matrix along each row
 -------------------------------------------------- 
 [[10 14 44 59 63]
 [11 37 38 60 61]
 [ 8 26 56 75 94]
 [12 35 39 40 45]
 [ 8 27 44 55 69]]

Here is the sorted matrix along each column
 -------------------------------------------------- 
 [[14 10 27  8  8]
 [26 11 35 12 45]
 [39 40 37 38 55]
 [44 56 63 44 59]
 [60 69 94 75 61]]


### 5.Create a,b,c  10 element vectors of random integers and perform the respective operation mentioned in print statement

In [42]:
# Fill the following ***** with appropriate solution.
a= ri(1,100,10)
b=ri(1,100,10)
c=ri(1,100,10)

print("a:", a)
print("b:", b)
print("c:", c)

print("Max of a:", a.max())
print("Max of b:",b.max())



print("Max of a location:", list(a).index(a.max()))
print("Max of b location:", list(b).index(b.max()))
print("Max of c location:", list(c).index(c.max()))

print("Max of a:", a.max())
print("Max of b:", b.max())


print("Max of a location:", list(a).index(a.max()))
print("Max of b location:", list(b).index(b.max()))
print("Max of c location:", list(c).index(c.max()))



a: [41 53 53 15 40 83 43 97 15 47]
b: [ 4 61 85 56 40 58 57 40 57 11]
c: [15 56 12 23 83 43 67 19 69 30]
Max of a: 97
Max of b: 85
Max of a location: 7
Max of b location: 2
Max of c location: 4
Max of a: 97
Max of b: 85
Max of a location: 7
Max of b location: 2
Max of c location: 4


## Universal functions

6. Create 3*3 matrices of random single-digit numbers.<br/>
Apply universal functions on it. (square root,exponetial,log10,Modulo etc.)

In [50]:

mat1 = np.asmatrix(ri(1,100,(3,3))) 
mat2 = np.asmatrix(ri(1,100,(3,3)))
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)


print("\nSq-root of 1st matrix using np\n------------------\n", np.sqrt(mat1))


print("\nExponential power of 1st matrix using np\n",'-'*50,"\n", np.power(mat1,2))


print("\n10-base logarithm on 1st matrix using np\n",'-'*50,"\n", np.log10(mat1))


print("\nModulo reminder using np\n",'-'*50,"\n", np.remainder(mat1,2))



1st Matrix of random single-digit numbers
----------------------------------------
 [[35 88 37]
 [23 57 54]
 [54 83 58]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[57 40 30]
 [66 52 97]
 [59 53 24]]

Sq-root of 1st matrix using np
------------------
 [[5.91607978 9.38083152 6.08276253]
 [4.79583152 7.54983444 7.34846923]
 [7.34846923 9.11043358 7.61577311]]

Exponential power of 1st matrix using np
 -------------------------------------------------- 
 [[1225 7744 1369]
 [ 529 3249 2916]
 [2916 6889 3364]]

10-base logarithm on 1st matrix using np
 -------------------------------------------------- 
 [[1.54406804 1.94448267 1.56820172]
 [1.36172784 1.75587486 1.73239376]
 [1.73239376 1.91907809 1.76342799]]

Modulo reminder using np
 -------------------------------------------------- 
 [[1 0 1]
 [1 1 0]
 [0 1 0]]


### 7.Generating matrices from distributions

In [67]:

print("Random number generation (from Uniform distribution)")
print(np.linspace(0,1,6).reshape(2,3))# 2 by 3 matrix with random numbers ranging from 0 to 1, Note no Tuple is necessary 

print("Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")
print(np.random.normal(1))

print("Random integer vector:",np.random.randint(1,100,10)) #randint (low, high, # of samples to be drawn)
print ("\nRandom integer matrix")
#print(********) #randint (low, high, # of samples to be drawn in a tuple to form a matrix)

print("\n20 samples drawn from a dice throw:",np.random.randint(1,6,20)) #20 samples drawn from a dice throw

Random number generation (from Uniform distribution)
[[0.  0.2 0.4]
 [0.6 0.8 1. ]]
Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal
2.293225882532262
Random integer vector: [53 77 69 46 65 90 41  8  8 34]

Random integer matrix

20 samples drawn from a dice throw: [3 3 5 3 5 1 3 5 5 2 2 2 2 5 4 5 2 2 2 3]


### 8.Find the nearest value from a given number in an array using NumPy.

In [66]:
#Steps
#Create an array of 5 random element from 1 to 12
x = np.random.uniform(1, 12, 5)
v =10
n = x.flat[np.abs(x - v).argmin()]
n
#Suppose find the nearest values of 10 in an array so set value=10
#find the index where difference is minimum and get the element

9.303476295295141

### 9.Write code using numpy to produce following output
[[0 0 0] [0 1 2] [0 2 4]]

In [72]:
array = np.array([0,0,0,0,1,2,0,2,4])
print(array.reshape(3,3))

[[0 0 0]
 [0 1 2]
 [0 2 4]]
